const spaceGroups = [
    // --- Triclinic ---
    {"number": 1, "name": "P1", "system": "triclinic", "laue_class": "-1", "rule_tree": {}},
    {"number": 2, "name": "P-1", "system": "triclinic", "laue_class": "-1", "rule_tree": {}},
    // --- Monoclinic ---
    {"number": 3, "name": "P2", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {}},
    {"number": 4, "name": "P21", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "0k0", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}},
    {"number": 5, "name": "C2", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {"type": "expression_check", "expression": "h+k", "divisor": 2}},
    {"number": 6, "name": "Pm", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {}},
    {"number": 7, "name": "Pc", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 8, "name": "Cm", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {"type": "expression_check", "expression": "h+k", "divisor": 2}},
    {"number": 9, "name": "Cc", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 10, "name": "P2/m", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {}},
    {"number": 11, "name": "P21/m", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "0k0", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}},
    {"number": 12, "name": "C2/m", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {"type": "expression_check", "expression": "h+k", "divisor": 2}},
    {"number": 13, "name": "P2/c", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 14, "name": "P21/c", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0k0", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}},
    {"number": 15, "name": "C2/c", "system": "monoclinic", "laue_class": "2/m", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    // --- Orthorhombic ---
    {"number": 16, "name": "P222", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {}},
    {"number": 17, "name": "P2221", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 18, "name": "P21212", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0k0", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}},
    {"number": 19, "name": "P212121", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0k0", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 20, "name": "C2221", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 21, "name": "C222", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"type": "expression_check", "expression": "h+k", "divisor": 2}},
    {"number": 22, "name": "F222", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}},
    {"number": 23, "name": "I222", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 24, "name": "I212121", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0k0", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 25, "name": "Pmm2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {}},
    {"number": 26, "name": "Pmc21", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}}, // CORRECTED

    {"number": 27, "name": "Pcc2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
{"number": 28, "name": "Pma2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}},

    {"number": 29, "name": "Pca21", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 30, "name": "Pnc2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}}, // CORRECTED

 


{"number": 31, "name": "Pmn21", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}]}},




    {"number": 32, "name": "Pba2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}},
    {"number": 33, "name": "Pna21", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}}, // CORRECTED
    {"number": 34, "name": "Pnn2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 2}]}},
    {"number": 35, "name": "Cmm2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"type": "expression_check", "expression": "h+k", "divisor": 2}},
  
    {"number": 36, "name": "Cmc21", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h", "divisor": 2}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}]}},

    {"number": 37, "name": "Ccc2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 38, "name": "Amm2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"type": "expression_check", "expression": "k+l", "divisor": 2}},
    {"number": 39, "name": "Abm2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}}, // CORRECTED

    {"number": 40, "name": "Ama2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}},
{"number": 41, "name": "Aba2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}},



    {"number": 42, "name": "Fmm2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}},
    {"number": 43, "name": "Fdd2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 4}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 4}]}]}},
    {"number": 44, "name": "Imm2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 45, "name": "Iba2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}},
    {"number": 46, "name": "Ima2", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}},
    {"number": 47, "name": "Pmmm", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {}},
    {"number": 48, "name": "Pnnn", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}]}},
    {"number": 49, "name": "Pccm", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},

    {"number": 50, "name": "Pban", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},


    {"number": 51, "name": "Pmma", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}},
   
   {"number": 52, "name": "Pnna", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}},

   
    {"number": 53, "name": "Pmna", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 2}]}]}}, // CORRECTED
    {"number": 54, "name": "Pcca", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}},
    {"number": 55, "name": "Pbam", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}},
    {"number": 56, "name": "Pccn", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 2}]}]}},
    {"number": 57, "name": "Pbcm", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 58, "name": "Pnnm", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 2}]}},

    {"number": 59, "name": "Pmmn", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}},


    {"number": 60, "name": "Pbcn", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}]}},
    {"number": 61, "name": "Pbca", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}},
    {"number": 62, "name": "Pnma", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}},
    {"number": 63, "name": "Cmcm", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 64, "name": "Cmce", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"logic": "AND", "rules": [{"type": "expression_check", "expression": "k", "divisor": 2}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 65, "name": "Cmmm", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"type": "expression_check", "expression": "h+k", "divisor": 2}},
    {"number": 66, "name": "Cccm", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 67, "name": "Cmma", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}},
    {"number": 68, "name": "Ccca", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}}, // CORRECTED
    {"number": 69, "name": "Fmmm", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}},
    {"number": 70, "name": "Fddd", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 4}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 4}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 4}]}]}},
    {"number": 71, "name": "Immm", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 72, "name": "Ibam", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}},
{"number": 73, "name": "Ibca", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}},
{"number": 74, "name": "Imma", "system": "orthorhombic", "laue_class": "mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}},



    // --- Tetragonal ---
    {"number": 75, "name": "P4", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {}},
    {"number": 76, "name": "P41", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 4}]}},
    {"number": 77, "name": "P42", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 78, "name": "P43", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 4}]}},
    {"number": 79, "name": "I4", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 80, "name": "I41", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 4}]}]}},
    {"number": 81, "name": "P-4", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {}},
    {"number": 82, "name": "I-4", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 83, "name": "P4/m", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {}},
    {"number": 84, "name": "P42/m", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 85, "name": "P4/n", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}},
    {"number": 86, "name": "P42/n", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 87, "name": "I4/m", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
{"number": 88, "name": "I41/a", "system": "tetragonal", "laue_class": "4/m", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h", "divisor": 2}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 4}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "2h+l", "divisor": 4}]}]}},

    {"number": 89, "name": "P422", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {}},
    {"number": 90, "name": "P4212", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}},
    {"number": 91, "name": "P4122", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 4}]}},
    {"number": 92, "name": "P41212", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 4}]}]}},
    {"number": 93, "name": "P4222", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 94, "name": "P42212", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}},
    {"number": 95, "name": "P4322", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 4}]}},
    {"number": 96, "name": "P43212", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 4}]}]}},
    {"number": 97, "name": "I422", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 98, "name": "I4122", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 4}]}]}},
    {"number": 99, "name": "P4mm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {}},
    {"number": 100, "name": "P4bm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}},
    {"number": 101, "name": "P42cm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}}, // CORRECTED
    {"number": 102, "name": "P42nm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}},
    {"number": 103, "name": "P4cc", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 104, "name": "P4nc", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}},
    {"number": 105, "name": "P42mc", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0k0", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}},
    {"number": 106, "name": "P42bc", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 107, "name": "I4mm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 108, "name": "I4cm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}},
    {"number": 109, "name": "I41md", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "2h+l", "divisor": 4}]}]}},
    {"number": 110, "name": "I41cd", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "2h+l", "divisor": 4}]}]}},
    {"number": 111, "name": "P-42m", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "0k0", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}},
    {"number": 112, "name": "P-42c", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0k0", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}},
    {"number": 113, "name": "P-421m", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {}},
    {"number": 114, "name": "P-421c", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 115, "name": "P-4m2", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {}},
    {"number": 116, "name": "P-4c2", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 117, "name": "P-4b2", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}},
    {"number": 118, "name": "P-4n2", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}},
    {"number": 119, "name": "I-4m2", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 120, "name": "I-4c2", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 121, "name": "I-42m", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0k0", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}},
    {"number": 122, "name": "I-42d", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "2h+l", "divisor": 4}]}]}},
    {"number": 123, "name": "P4/mmm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {}},
    {"number": 124, "name": "P4/mcc", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 125, "name": "P4/nbm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}},
    {"number": 126, "name": "P4/nnc", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}},
    {"number": 127, "name": "P4/mbm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}},
    {"number": 128, "name": "P4/mnc", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 2}]}},
    {"number": 129, "name": "P4/nmm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}},
    {"number": 130, "name": "P4/ncc", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 131, "name": "P42/mmc", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0k0", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}},
    {"number": 132, "name": "P42/mcm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0k0", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}},
    {"number": 133, "name": "P42/nbc", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 134, "name": "P42/nnm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 2}]}]}},
    {"number": 135, "name": "P42/mbc", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 136, "name": "P42/mnm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}]}}, // CORRECTED
    {"number": 137, "name": "P42/nmc", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}}, // CORRECTED
    {"number": 138, "name": "P42/ncm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}}, // CORRECTED
    {"number": 139, "name": "I4/mmm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 140, "name": "I4/mcm", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 141, "name": "I41/amd", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "2h+l", "divisor": 4}]}]}},
    {"number": 142, "name": "I41/acd", "system": "tetragonal", "laue_class": "4/mmm", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"logic": "AND", "rules": [{"type": "expression_check", "expression": "k", "divisor": 2}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "2h+l", "divisor": 4}]}]}},
// --- Trigonal --- (Hexagonal Axes)

{"number": 143, "name": "P3", "system": "trigonal", "laue_class": "-3", "rule_tree": {}},
{"number": 144, "name": "P31", "system": "trigonal", "laue_class": "-3", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 3}]}},
{"number": 145, "name": "P32", "system": "trigonal", "laue_class": "-3", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 3}]}},
{"number": 146, "name": "R3", "system": "trigonal", "laue_class": "-3", "rule_tree": {"type": "expression_check", "expression": "-h+k+l", "divisor": 3}},
{"number": 147, "name": "P-3", "system": "trigonal", "laue_class": "-3", "rule_tree": {}},
{"number": 148, "name": "R-3", "system": "trigonal", "laue_class": "-3", "rule_tree": {"type": "expression_check", "expression": "-h+k+l", "divisor": 3}},
{"number": 149, "name": "P312", "system": "trigonal", "laue_class": "-3m", "rule_tree": {}},
{"number": 150, "name": "P321", "system": "trigonal", "laue_class": "-3m", "rule_tree": {}},
{"number": 151, "name": "P3112", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 3}]}},
{"number": 152, "name": "P3121", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 3}]}},
{"number": 153, "name": "P3212", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 3}]}},
{"number": 154, "name": "P3221", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 3}]}},
{"number": 155, "name": "R32", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"type": "expression_check", "expression": "-h+k+l", "divisor": 3}},
{"number": 156, "name": "P3m1", "system": "trigonal", "laue_class": "-3m", "rule_tree": {}},
{"number": 157, "name": "P31m", "system": "trigonal", "laue_class": "-3m", "rule_tree": {}},
{"number": 158, "name": "P3c1", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
{"number": 159, "name": "P31c", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
{"number": 160, "name": "R3m", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"type": "expression_check", "expression": "-h+k+l", "divisor": 3}},
{"number": 161, "name": "R3c", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "-h+k+l", "divisor": 3}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
{"number": 162, "name": "P-31m", "system": "trigonal", "laue_class": "-3m", "rule_tree": {}},
{"number": 163, "name": "P-31c", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
{"number": 164, "name": "P-3m1", "system": "trigonal", "laue_class": "-3m", "rule_tree": {}},
{"number": 165, "name": "P-3c1", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
{"number": 166, "name": "R-3m", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"type": "expression_check", "expression": "-h+k+l", "divisor": 3}},
{"number": 167, "name": "R-3c", "system": "trigonal", "laue_class": "-3m", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "-h+k+l", "divisor": 3}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
// --- Hexagonal ---
    {"number": 168, "name": "P6", "system": "hexagonal", "laue_class": "6/m", "rule_tree": {}},
    {"number": 169, "name": "P61", "system": "hexagonal", "laue_class": "6/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 6}]}},
    {"number": 170, "name": "P65", "system": "hexagonal", "laue_class": "6/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 6}]}},
    {"number": 171, "name": "P62", "system": "hexagonal", "laue_class": "6/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 3}]}},
    {"number": 172, "name": "P64", "system": "hexagonal", "laue_class": "6/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 3}]}},
    {"number": 173, "name": "P63", "system": "hexagonal", "laue_class": "6/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 174, "name": "P-6", "system": "hexagonal", "laue_class": "6/m", "rule_tree": {}},
    {"number": 175, "name": "P6/m", "system": "hexagonal", "laue_class": "6/m", "rule_tree": {}},
    {"number": 176, "name": "P63/m", "system": "hexagonal", "laue_class": "6/m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 177, "name": "P622", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {}},
    {"number": 178, "name": "P6122", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 6}]}},
    {"number": 179, "name": "P6522", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 6}]}},
    {"number": 180, "name": "P6222", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 3}]}},
    {"number": 181, "name": "P6422", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 3}]}},
    {"number": 182, "name": "P6322", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 183, "name": "P6mm", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {}},
    {"number": 184, "name": "P6cc", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 185, "name": "P63cm", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 186, "name": "P63mc", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 187, "name": "P-6m2", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {}},
    {"number": 188, "name": "P-6c2", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 189, "name": "P-62m", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {}},
    {"number": 190, "name": "P-62c", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 191, "name": "P6/mmm", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {}},
    {"number": 192, "name": "P6/mcc", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}},
    {"number": 193, "name": "P63/mcm", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 194, "name": "P63/mmc", "system": "hexagonal", "laue_class": "6/mmm", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "00l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    // --- Cubic ---
    {"number": 195, "name": "P23", "system": "cubic", "laue_class": "m-3", "rule_tree": {}},
    {"number": 196, "name": "F23", "system": "cubic", "laue_class": "m-3", "rule_tree": {"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}},
    {"number": 197, "name": "I23", "system": "cubic", "laue_class": "m-3", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 198, "name": "P213", "system": "cubic", "laue_class": "m-3", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}},
    {"number": 199, "name": "I213", "system": "cubic", "laue_class": "m-3", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}},
    {"number": 200, "name": "Pm-3", "system": "cubic", "laue_class": "m-3", "rule_tree": {}},
    {"number": 201, "name": "Pn-3", "system": "cubic", "laue_class": "m-3", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}]}}, // CORRECTED
    {"number": 202, "name": "Fm-3", "system": "cubic", "laue_class": "m-3", "rule_tree": {"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}},
    {"number": 203, "name": "Fd-3", "system": "cubic", "laue_class": "m-3", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 4}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 4}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 4}]}]}}, // CORRECTED
    {"number": 204, "name": "Im-3", "system": "cubic", "laue_class": "m-3", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 205, "name": "Pa-3", "system": "cubic", "laue_class": "m-3", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}]}}, // CORRECTED
    {"number": 206, "name": "Ia-3", "system": "cubic", "laue_class": "m-3", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"logic": "AND", "rules": [{"type": "expression_check", "expression": "k", "divisor": 2}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h", "divisor": 2}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h", "divisor": 2}, {"type": "expression_check", "expression": "k", "divisor": 2}]}]}]}}, // CORRECTED
    {"number": 207, "name": "P432", "system": "cubic", "laue_class": "m-3m", "rule_tree": {}},
    {"number": 208, "name": "P4232", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 2}]}},
    {"number": 209, "name": "F432", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}},
    {"number": 210, "name": "F4132", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 4}]}]}},
    {"number": 211, "name": "I432", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 212, "name": "P4332", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 4}]}},
    {"number": 213, "name": "P4132", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 4}]}},
    {"number": 214, "name": "I4132", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h00", "inverse": true}, {"type": "expression_check", "expression": "h", "divisor": 4}]}]}},
    {"number": 215, "name": "P-43m", "system": "cubic", "laue_class": "m-3m", "rule_tree": {}},
    {"number": 216, "name": "F-43m", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}},
    {"number": 217, "name": "I-43m", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
{"number": 218, "name": "P-43n", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}},

    {"number": 219, "name": "F-43c", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}}, // CORRECTED
    {"number": 220, "name": "I-43d", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "2h+l", "divisor": 4}]}]}},
    {"number": 221, "name": "Pm-3m", "system": "cubic", "laue_class": "m-3m", "rule_tree": {}},
{"number": 222, "name": "Pn-3n", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k", "divisor": 2}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}},

    {"number": 223, "name": "Pm-3n", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 2}]}]}}, // CORRECTED
    {"number": 224, "name": "Pn-3m", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "h0l", "inverse": true}, {"type": "expression_check", "expression": "h+l", "divisor": 2}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hk0", "inverse": true}, {"type": "expression_check", "expression": "h+k", "divisor": 2}]}]}}, // CORRECTED
    {"number": 225, "name": "Fm-3m", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}},
    {"number": 226, "name": "Fm-3c", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 227, "name": "Fd-3m", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 4}]}]}},
    {"number": 228, "name": "Fd-3c", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "AND", "rules": [{"logic": "OR", "rules": [{"type": "parity", "rule": "all_even"}, {"type": "parity", "rule": "all_odd"}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"type": "expression_check", "expression": "k+l", "divisor": 4}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}},
    {"number": 229, "name": "Im-3m", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"type": "expression_check", "expression": "h+k+l", "divisor": 2}},
    {"number": 230, "name": "Ia-3d", "system": "cubic", "laue_class": "m-3m", "rule_tree": {"logic": "AND", "rules": [{"type": "expression_check", "expression": "h+k+l", "divisor": 2}, {"logic": "OR", "rules": [{"type": "family_check", "family": "0kl", "inverse": true}, {"logic": "AND", "rules": [{"type": "expression_check", "expression": "k", "divisor": 2}, {"type": "expression_check", "expression": "l", "divisor": 2}]}]}, {"logic": "OR", "rules": [{"type": "family_check", "family": "hhl", "inverse": true}, {"type": "expression_check", "expression": "2h+l", "divisor": 4}]}]}}
];